name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: >
          sudo apt install --no-install-recommends --yes
          build-essential meson pkg-config wayland-protocols
          libwayland-dev libcairo-dev libjson-c-dev
          libgif-dev libjpeg-dev librsvg2-dev libwebp-dev

    - name: Configure
      run: meson --buildtype release --prefix /usr ./build
    - name: Build
      run: ninja -C ./build
    - name: Install
      run: DESTDIR=install ninja -C ./build install
    - name: Check
      run: ./build/install/usr/bin/swayimg --version

    - name: Create AppImage
      run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x ./linuxdeploy-x86_64.AppImage
          ./linuxdeploy-x86_64.AppImage --appdir ./build/install --desktop-file swayimg.desktop --icon-file swayimg.png --output appimage

    - uses: actions/upload-artifact@v2
      with:
          name: swayimg-x86_64
          path: swayimg-*-x86_64.AppImage
