name: CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: >
          sudo apt install --no-install-recommends --yes
          build-essential meson pkg-config wayland-protocols
          libwayland-dev libcairo-dev libjson-c-dev libxkbcommon-dev
          libpango1.0-dev libpangocairo-1.0-0
          libavif-dev libgif-dev libjpeg-dev librsvg2-dev libwebp-dev

    - name: Check out source code
      uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0

    - name: Get version
      run: echo "::set-output name=VERSION::$(git describe --tags --long --always | sed 's/^v//;s/-/./')"
      id: version

    - name: Configure
      run: meson -Dversion=${{steps.version.outputs.VERSION}} --buildtype release --prefix /usr ./build
    - name: Build
      run: ninja -C ./build
    - name: Install
      run: DESTDIR=install ninja -C ./build install
    - name: Check
      run: ./build/install/usr/bin/swayimg --version
