name: FreeBSD/x86_64
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      BUILD_PATH: /tmp/build
      INSTALL_PATH: /tmp/install

    steps:
    - name: Check out source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: FreeBSD check
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: >
          pkg install -y
          meson pkgconf
          bash-completion json-c freetype2 fontconfig
          libinotify libxkbcommon libexif
          wayland wayland-protocols
          libavif libjxl libsixel librsvg2-rust
          giflib jpeg-turbo openexr png tiff webp
          googletest
        run: |
          set -e
          meson setup --werror -D tests=enabled -D heif=auto -D bash=enabled -D exif=enabled -D exr=enabled -D gif=enabled -D jpeg=enabled -D jxl=auto -D svg=enabled -D tiff=enabled -D sixel=enabled -D webp=enabled -D man=true -D desktop=true --prefix=/usr ${{ env.BUILD_PATH }}
          meson compile -C ${{ env.BUILD_PATH }}
          meson test --verbose -C ${{ env.BUILD_PATH }}
          DESTDIR=${{ env.INSTALL_PATH }} meson install -C ${{ env.BUILD_PATH }}
          tar czf swayimg-freebsd.tar.gz -C ${{ env.INSTALL_PATH }} .

    - name: Upload binary package
      uses: actions/upload-artifact@v4
      with:
        name: swayimg-freebsd.tar.gz
        path: swayimg-freebsd.tar.gz
