name: FreeBSD
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      BUILD_PATH: /tmp/build
      INSTALL_PATH: /tmp/install

    steps:
    - uses: actions/checkout@v4
    - name: FreeBSD check
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: >
          pkg install -y
          meson pkgconf
          wayland wayland-protocols libxkbcommon freetype2 fontconfig
          json-c libinotify googletest
          libavif giflib libheif libjxl libexif openexr png tiff webp jpeg-turbo
        run: |
          meson setup -Dtests=enabled --prefix=/usr ${{ env.BUILD_PATH }}
          meson compile -C ${{ env.BUILD_PATH }}
          env DESTDIR=${{ env.INSTALL_PATH }} meson install -C ${{ env.BUILD_PATH }}
          ${{ env.INSTALL_PATH }}/usr/bin/swayimg --version
          meson test --verbose -C ${{ env.BUILD_PATH }}
